services:
  cpp-builder:
    build:
      context: .
      dockerfile: builder.dockerfile
    volumes:
      - ./build:/output
    command: >
      sh -c "cp /src/build/mini_blockchain /output/ && echo 'Binary copied'"
    restart: "no"

  cpp-runner:
    tty: true
    build:
      context: .
      dockerfile: runner.dockerfile
    depends_on:
      - cpp-builder
    networks:
      - my_network
    deploy:
      replicas: 5
      resources:
        limits:
          memory: 1G    # Allocate 1 GB of memory to each replica
        reservations:
          memory: 500M  # Reserve 500 MB of memory per replica
    restart: "no"

networks:
  my_network:
    driver: bridge