#ifndef P_OS_SRC_NET_CONSTS_H
#define P_OS_SRC_NET_CONSTS_H

#define NET_BROADCAST_PORT 19814
#define NET_MASTER_PORT 19815

#define SERVER_DISCOVERY_MESSAGE "SERVER_DISCOVERY"
    
#endif /* P_OS_SRC_NET_CONSTS_H */
